### PR TITLE
Also test on iojs 2

### PR DESCRIPTION
**Pull request by ricordisamoa**

### CODE REVIEW

**Comment by ricordisamoa** [comment]
Build failed at https://travis-ci.org/ricordisamoa/node-rsvg/builds/81140103

By the way, it should be ported to Node.js 4

**Comment by Delapouite** [comment]
I confirm this great lib is unfortunately broken on Node 4

**Comment by ricordisamoa** [comment]
@heilage-nsk do you know how to use the newest NAN?
Thanks in advance.

**Comment by ctizen** [comment]
@ricordisamoa 
Yes, it's almost done but not tested yet. Here is my working branch: https://github.com/heilage-nsk/node-rsvg/tree/port-to-nodev4
I will test and publish it this week.

**Comment by ricordisamoa** [comment]
Thanks again!

**Comment by ricordisamoa** [comment]
FYI Node 5 [went out](//nodejs.org/en/blog/release/v5.0.0/) last week, although "v4 is going to live for a lot longer".

**Comment by ctizen** [comment]
@ricordisamoa the supported nodersvg repo has been forked to https://github.com/2gis/node-rsvg
Thanks for mentioning about new node version, I'll take a look at it soon :)

**Comment by ricordisamoa** [comment]
Thank you @heilage-nsk for mentioning the new version, I'll keep track of the forks!

**Pull request merged**
